# contains necessary dependencies for application
name: woundcare_app
description: A new Flutter application for woundcare app.
dependencies: 
  flutter: 
    sdk: flutter
  file_picker: ^4.0.0
  dio: ^4.0.0
  path_provider: ^2.0.15
  flutter_aws_s3_client: ^0.6.0
  aws_s3_upload: ^1.5.0
  amplify_storage_s3: ^2.1.0
  simple_s3: ^0.3.2

environment:
  sdk: '^3.4.0'
dev_dependencies:
  flutter_lints: ^4.0.0
